### ISSUE TITLE
Initial suggestions for plugin release

### ISSUE THREAD

**Issue by misraved** [gdebus/steampipe-plugin-openstack#1]
Thanks @gdebus for this new plugin. Great work 🎉 !!

The basic structure looks good so far. While using the plugin, we did come up with a few suggestions based on our best practices:

- `config/openstack.spc`
  - Is there a specific reason why the plugin has been named as `local/openstack` instead of `gdebus/openstack`? In general, we refer to the repo name for reference to the plugins - https://github.com/marekjalovec/steampipe-plugin-make/blob/main/config/make.spc#L2
  - The `openstack.spc` file looks great with all the details of the authentication arguments, however, it looks slightly confusing in terms of which arguments are required and which ones are optional. Please take a look at [namecheap](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/config/namecheap.spc) plugin's config file for more information. In general, for new plugin users, I believe it is important to address the mandatory and optional arguments so that the initial process of plugin use becomes easier.
  - Do we have a doc that we could link to in the `openstack.spc` file to fetch the authentication arguments? I think overall it would be helpful for the users to figure out a way to navigate to the config arguments on the OpenStack console.

- `docs/tables/*`
  - Overall the docs look great, the queries are neat, however, I feel that we still have a scope to add 1-2 more additional queries per table. I was browsing through the available columns and felt we could have more example queries. For instance, In https://github.com/gdebus/steampipe-plugin-openstack/blob/main/docs/tables/openstack_compute_image.md, we could add the following example queries - 
    - `List compute images created in the last 30 days`
    - `List compute images that haven't been updated in the last 90 days`
  - A similar format could be followed for `openstack_fip`, `openstack_volume` table docs etc.

- `docs/index.md` and `README` 
  - The doc files look great. You could make minor formatting updates per the [namecheap](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/README.md) plugin docs
  - The references to the social-graphics and icons should be updated to use `gdebus` instead of `turbot`. For instance, `icon_url: "/images/plugins/turbot/openstack.svg"` should be updated to use `icon_url: "/images/plugins/gdebus/openstack.svg"`. You could take a look at https://github.com/marekjalovec/steampipe-plugin-make/blob/main/docs/index.md for more reference.
  - The plugin installation command should be updated to use `steampipe plugin install gdebus/openstack` instead of `steampipe plugin install openstack`.
  - The organization section should be updated to use `gdebus` instead of `Turbot`.
  
- `go.mod`
    - Please update the Steampipe plugin SDK to use the latest `5.4.1` version

- `Makefile`
    - Please update the install command as follows - 
        `go build -o ~/.steampipe/plugins/hub.steampipe.io/plugins/gdebus/openstack@latest/steampipe-plugin-openstack.plugin *.go`
        
- openstack/*
  - The table structure, column names and the logging section look great. very neat indeed 👍!!
  - While browsing through the API docs, I found instances wherein the GetConfig hasn't been implemented. For instance in https://github.com/gdebus/steampipe-plugin-openstack/blob/main/openstack/table_openstack_compute_image.go we have just addressed the `ListConfig` section, however, per http://gophercloud.io/docs/compute/#get-image, we could also add support for the `GetConfig`.  Please refer https://steampipe.io/docs/develop/writing-plugins#get-config for more information
  - Overall we should sweep through the API docs and add the `GetConfig` for all the supported tables.
  - Is there a specific reason why we named the table as `openstack_applicationcredential` instead of `openstack_application_credential`
  
- A couple of follow-up questions:
    - How are we handling the resource not found errors?
    - It looks like the API supports pagination, did we handle it correctly?
    - While working with the APIs did you encounter rate limit errors? 
    - Please refer https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion for more information
    
Overall the plugin looks great @gdebus. Thanks for all the effort. Please let us know if you have questions. Happy to help 👍.
Once the suggestion/feedback comments are addressed, we could release it to the hub 👍.

**Comment by gdebus** [comment]
Thanks for all the feedback @misraved!

Following progress was made in the last week:

- `config/openstack.spc`
   - Fixed in commit f85aaec
- `docs/tables/`
   - fixed in commit 6316f7c
-   `docs/index.md` and `README`
    - fixed in commit a28773f
- `go.mod`
   - fixed in commit 160e381
- `Makefile`
   - fixed in commit 80e76ce
- openstack/*
   - fixed in commit 160e381
- Follow-up questions:
   - So far correctly implemented. Gophercloud does not allow limiting page size.
   - As of now, the API does not implement rate limiting.

**IMPORTANT: This repository has been moved for the release to https://github.com/ernw/steampipe-plugin-openstack. Please create new issues there as this repository will not be updated in the future.**
